name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release (e.g., v1.0.1)'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install dependencies
        run: go mod tidy

      - name: Create Output Directory
        run: mkdir bin

      - name: Build for Windows
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -ldflags="-s -w" -o bin/curecode-windows-amd64.exe main.go

      - name: Build for Linux (AMD64)
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -ldflags="-s -w" -o bin/curecode-linux-amd64 main.go

      - name: Build for Linux (ARM64)
        env:
          GOOS: linux
          GOARCH: arm64
        run: go build -ldflags="-s -w" -o bin/curecode-linux-arm64 main.go

      - name: Build for macOS (Intel)
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -ldflags="-s -w" -o bin/curecode-macos-amd64 main.go

      - name: Build for macOS (Silicon)
        env:
          GOOS: darwin
          GOARCH: arm64
        run: go build -ldflags="-s -w" -o bin/curecode-macos-arm64 main.go

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          files: bin/*
          generate_release_notes: true
          draft: false
          prerelease: false
